<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>io.fixprotocol.orchestra</groupId>
	<artifactId>fixml-generator</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>${project.groupId}:${project.artifactId}</name>
	<description>FIXML schema generator from from Orchestra / FIX Repository 2016 Edition</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<saxon.version>9.8.0-8</saxon.version>
		<junit.version>4.11</junit.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>net.sf.saxon</groupId>
			<artifactId>Saxon-HE</artifactId>
			<version>${saxon.version}</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
			<version>${junit.version}</version>
		</dependency>
	</dependencies>
</project>